import Head from "next/head";
import Link from "next/link";

import button from "@/styles/button.module.css";
import styles from "@/styles/Home.module.css";

import avatar from "./assets/images/avatar.png";
import tech from "./assets/images/eyes.png";
import project from "./assets/images/project.png";

import Navbar from "@/component/navbar/navbar";

import AOS from "aos";
import "aos/dist/aos.css";

import { useEffect } from "react";

import { AiOutlineArrowDown } from "react-icons/ai";
import Image from "next/image";

export default function Home() {
  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <>
      <Head>
        <title>Haris Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <header className={styles.header}>
          <div id="background-wrap">
            <div className="x1">
              <div className="cloud"></div>
            </div>

            <div className="x2">
              <div className="cloud"></div>
            </div>

            <div className="x3">
              <div className="cloud"></div>
            </div>

            <div className="x4">
              <div className="cloud"></div>
            </div>

            <div className="x5">
              <div className="cloud"></div>
            </div>
          </div>
          <h1 className={styles.title}>
            Hello, my name is <span className={styles.name}>Haris Maulana</span>
            <br />I am a <span className={styles.name}>Software engineer</span>
          </h1>
        </header>
        <p className={styles.mainTitle}>
          <span className={styles.arrowDown}>
            <AiOutlineArrowDown />
          </span>
        </p>
        <div className={styles.containerProject}>
          <div className={styles.cardContainer}>
            <div
              className={styles.card}
              data-aos="fade-up"
              data-aos-duration="600"
            >
              <Image src={avatar} alt="avatar" className={styles.icons} />
            </div>
            <h3
              className={styles.iconsTitle}
              data-aos="fade-right"
              data-aos-duration="1000"
            >
              ABOUT ME
            </h3>
          </div>
          <div className={styles.cardContainer}>
            <div
              className={styles.card}
              data-aos="fade-up"
              data-aos-duration="600"
            >
              <Image src={tech} alt="tech" className={styles.icons} />
            </div>
            <h3
              className={styles.iconsTitle}
              data-aos="fade-right"
              data-aos-duration="1000"
            >
              Technologies
            </h3>
          </div>
          <div className={styles.cardContainer}>
            <div
              className={styles.card}
              data-aos="fade-up"
              data-aos-duration="600"
            >
              <Image src={project} alt="project" className={styles.icons} />
            </div>
            <h3
              className={styles.iconsTitle}
              data-aos="fade-right"
              data-aos-duration="1000"
            >
              Project
            </h3>
          </div>
        </div>
      </main>
    </>
  );
}
